<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var \Codazon\ThemeLayoutPro\Block\Html\StoreLanguageCurrency $block */
$languageHtml = trim($block->getChildHtml('language_switcher'));
$currencyHtml = trim($block->getChildHtml('currency_switcher'));
$storeName = $block->getStoreName();
$currencyCode = $block->getCurrencyCode();
?>
<?php if ($languageHtml || $currencyHtml) : ?>
<li class="store-language-currency">
    <div class="account-wrapper cdz-dropdown"  data-role="cdz-dropdown">
        <a href="javascript:;" class="account-trigger cdz-dd-trigger" data-role="cdz-dd-trigger">
            <span class="text-underlink"><?= $block->escapeHtml(__('Language')) ?></span>
            <span class="text-uppercase">
                <span class="language"><?= $block->escapeHtml($storeName) ?></span>
                <span class="currency"><?= $block->escapeHtml($currencyCode) ?></span>
            </span>
        </a>
        <div class="cdz-dd-content wl-drop-menu" data-role="cdz-dd-content">
            <div class="cdz-dd-content-inner">
                <div class="acount-menu">
                    <ul class="account-menu-items items">
                        <?php if ($languageHtml) : ?>
                        <li class="language-link"><?= $languageHtml; ?></li>
                        <?php endif ?>
                        <?php if ($currencyHtml) : ?>
                        <li class="currency-link"><?= $currencyHtml; ?></li>
                        <?php endif ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</li>
<?php endif ?>
