<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>
<style type="text/css">
.page-footer .switcher .options .action.toggle:after{display: none !important;}
.page-footer .switcher-language .switcher-trigger a{font-family: tahoma;}
</style>
<?php if (count($block->getStores())>1): ?>
<?php $id = uniqid(); ?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>">
            <?php foreach ($block->getStores() as $_lang): ?>
            <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
            <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'> 
                        
                            <span class="lang-name"><?php echo $block->escapeHtml($_lang->getName()) ?></span>
                        </a>
                        <?php endif; ?>
                        <?php endforeach; ?>
        </div>
      <!--  <ul class="dropdown switcher-dropdown"
            data-mage-init='{"dropdownDialog":{
                "appendTo":"#switcher-language<?php /* @escapeNotVerified */ echo $id ?> > .options",
                "triggerTarget":"#switcher-language-trigger<?php /* @escapeNotVerified */ echo $id ?>",
                "closeOnMouseLeave": false,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":null}}'>
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                    <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'> 
                            <img class="lang-img" alt="<?php echo $block->escapeHtml($_lang->getName()) ?>" src="<?php echo $block->getViewFileUrl('images/flags/flag_' . $_lang->getCode() . '.gif') ?>" />
                            <span class="lang-name"><?php echo $block->escapeHtml($_lang->getName()) ?></span>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul> -->
    </div>
</div>
<?php endif; ?>
