<div class="message success message-success">
    <div>You will be redirect to cart page shortly.</div>
</div>

<script type="text/javascript">
    require([
        'jquery',
        'mage/storage',
        'Magento_Customer/js/customer-data',
        'mage/url',
    ], function ($, storage, customerData, url) {
        var sections = ['cart'];
        customerData.initStorage()
        customerData.invalidate(sections);
        customerData.reload(sections, true);
        window.location.href = url.build('checkout/cart');
    });
</script>
